### ISSUE TITLE
Request : AuditPolicyCsv include FileHash parameter

### ISSUE THREAD

**Issue by bdanse** [athaynes/xAuditPolicy#31]
From a security point of view, how do I know the file that is being imported is not modified. 
A filehash check would be a nice addition to this great module. 

For example run get-filehash against "C:\data\AuditPolBackup.csv". And include the Hash result in the resource

``Configuration Sample_AuditPolicyCsv
{
    param
    (
        [String] $NodeName = 'localhost'
    )    
   
    Import-DscResource -ModuleName AuditPolicyDsc

    Node $NodeName
    {
        AuditPolicyCsv auditPolicy
        {
            IsSingleInstance = 'Yes'
            CsvPath = "C:\data\AuditPolBackup.csv"
	    FileHash = '9A7C892496CFAA5CF8CC2BDDCC255E15CEDF95997F87FF8913E5DB7EB17A006B'
        }
    }
}

Sample_AuditPolicyCsv

**Comment by zjalexander** [comment]
discussion is at https://github.com/PowerShell/GPRegistryPolicy/issues/2

**Comment by athaynes** [comment]
@zjalexander Can we can close this issues based on the conversation at https://github.com/PowerShell/GPRegistryPolicy/issues/2

**Comment by zjalexander** [comment]
yeah
