### ISSUE TITLE
Csv Path Conflicts if we use  AuditPolicyCsv multiple times

### ISSUE THREAD

**Issue by narendarchandha** [athaynes/xAuditPolicy#33]
Hi,
I am using AuditPolicyCsv in my DSC Configuration for Windows Hardening.
So i am making my script more simple by providing configuration data through hash table.

Here is the configuration i am using

` 
 $BaseOsConfig=
@{
    AllNodes = 
    @(
         @{ 
            NodeName = 'localhost'
           AuditPolicies = @{
                                Name      = 'Feature_Audit';
                                Path       = "C:\WindowsHardening\Feature.Auditing\lgpo.audit.csv";
                                },
                              @{
                                Name      = 'Role_Server';
                                Path       = "C:\WindowsHardening\Role.Server\lgpo.audit.csv";
                                }
           }
     )
}
`
`
 Configuration SecurityTest
 {
    Import-DscResource -ModuleName SecurityPolicyDSC
    Import-DscResource -ModuleName AuditPolicyDsc

    Node Localhost
    {
        foreach ($file in $Node.AuditPolicies) 
        { 
         Write-Verbose -Message ("Loading Audit Policy File for {0}" -f $file.Name)
    	AuditPolicyCsv $file.Name
                {
                CsvPath = $file.Path
                IsSingleInstance = 'Yes'
               }
    	}
    }
}
`
`SecurityTest -ConfigurationData $BaseOsConfig -verbose -OutPutPath E:\naren\Naren_Testings  
Start-DscConfiguration -Path E:\naren\Naren_Testings -Wait -Verbose -Force `

This script  gives me error :
-----------------------------------------
`VERBOSE: Loading Audit Policy File for Feature_Audit
VERBOSE: Loading Audit Policy File for Role_Server
Test-ConflictingResources : A conflict was detected between resources '[AuditPolicyCsv]Feature_Audit (::30::6::AuditPolicyCsv)' and '[AuditPolicyCsv]Role_Server (::30::6::AuditPolicyCsv)' in node 'Localhost'. Resources have identical 
key properties but there are differences in the following non-key properties: 'CsvPath'. Values 'C:\WindowsHardening\Feature.Auditing\lgpo.audit.csv' don't match values 'C:\WindowsHardening\Role.Server\lgpo.audit.csv'. Please update 
these property values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : ConflictingDuplicateResource,Test-ConflictingResources
Compilation errors occurred while processing configuration 'SecurityTest'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SecurityTest:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration`
 

Workaround i made in my VM
--------------------------------
**Just to overcome this issue , i have changed "CsvPath"  property attribute from 'Required' to 'Key' @  
"C:\ProgramFiles\WindowsPowerShell\Modules\AuditPolicyDsc\1.1.0.0\DSCResources\MSFT_AuditPolicyCsv\MSFT_AuditPolicyCsv.schema.mof"**

Now this script is processing and i can see the .mof is running with out any errors.

The same error with  SecurityTemplate also @ https://github.com/PowerShell/SecurityPolicyDsc/tree/dev/DSCResources/MSFT_SecurityTemplate 
I just changed the "Path" Atttribute to Key from Required.  

**I would just like to Notify the Authors about the error, so they can made the fix  or may be they can suggest the other way to fix them.**

**Thank you..**

**Comment by athaynes** [comment]
The problem I see here is that there is no way to deconflict settings between your CSV files. If the second file steps on a setting from the first file the resource will detect and "fix it", but then you will never be complaint with the first file. Would it be better to merge your CSV files and deconflict your data before giving it to DSC to implement?

**Comment by athaynes** [comment]
@narendarchandha I never heard back from you and wanted to see if I can close this issue.
