### ISSUE TITLE
AuditPolicySubcategory Ensure default value missing in Test-TargetResource

### ISSUE THREAD

**Issue by bdanse** [athaynes/xAuditPolicy#39]
AuditPolicySubcategory "NOT_ASSIGNED: Ensure 'Audit PNP Activity' is set to 'Success'"
{
 	Name = 'Plug and Play Events'
 	AuditFlag = 'Success'

}
Will not result in a desired state. It keeps testing the result. 
The following will work though. 

AuditPolicySubcategory "NOT_ASSIGNED: Ensure 'Audit PNP Activity' is set to 'Success'"
{
 	Name = 'Plug and Play Events'
 	AuditFlag = 'Success'
 	Ensure = 'Present'
}

The documentation state the default value for Ensure is present. It is set for the Set-TargetResource  but not the Test-TargetResourse ensure parameter.

**Comment by athaynes** [comment]
Nice catch. I have a list of other changes in the works and will add this now.
