### ISSUE TITLE
how to export security policy to csv file and how to restore from csv?how to audit to check whether policy applied?

### ISSUE THREAD

**Issue by hoyeunglee** [athaynes/xAuditPolicy#41]
how to export security policy to csv file and how to restore from csv? is there two examples?
how to audit to check whether policy applied? such as length of password etc?
is it to check the csv file ?

**Comment by johlju** [comment]
I think you are looking for [SecurityPolicy](https://github.com/PowerShell/SecurityPolicyDsc).

But if you mean setting audit policy.

How to backup audit policy see here; 
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/auditpol-backup

Then you have to build a DSC configuration like the following examples; https://github.com/PowerShell/AuditPolicyDsc/tree/dev/Examples
