### ISSUE TITLE
AuditPolicySubcategory should support an array of AuditFlags

### ISSUE THREAD

**Issue by BernieWhite** [athaynes/xAuditPolicy#43]
In many cases it is necessary to set both Success and Failure audit flags. The `AuditFlag` property of `AuditPolicySubcategory` should support an array of audit flags.

This would make using this resource significantly less time consuming. Additionally this may also improve performance and reduce the verbosity of the configuration scripts.

**Comment by BernieWhite** [comment]
Also related to #40

**Comment by johlju** [comment]
It's not possible having an array as Key. If we would change `AuditFlag` to an array and type qualifier `Write`,  looking at the blow snippet, would that mean that `'Failure'` would be removed if it was set?
In this scenario if one user want's to remove `'Failure'`, but another user want's to keep `'Failure'` if it is set, how would we solve that? 🤔 

```
AuditPolicySubcategory LogonSuccess
{
    Name      = 'Logon'
    AuditFlag = @('Success')
    Ensure    = 'Present'
}
```

**Comment by athaynes** [comment]
@BernieWhite for your scenario, AuditPolicyCSV has the lowest overhead. The reason 'Success and Failure' is not allowed in the schema, is because the LCM wouldn't be able to detect a setting conflict. The following configuration would never be compliant because the AuditFlag key value is different from DSC's perspective, but they set the same bit in auditpol. 
```powershell
Configuration AuditLogon {
    Import-DscResource -ModuleName 'AuditPolicyDsc'
    Node localhost {
        AuditPolicySubcategory LogonSuccess
        {
            Name      = "Logon"
            AuditFlag = "Success and Failure"
            Ensure    = "Present"
        }

        AuditPolicySubcategory LogonFailure
        {
            Name      = "Logon"
            AuditFlag = "Failure"
            Ensure    = "Absent"
        }
    }
}   
```

**Comment by BernieWhite** [comment]
So why isn't the key Name/SubCategory? That is the most logical key.

Clearing/setting of both success and failure can easily be accomodated by using a property to indicate if the flag is additive or complete.

**Comment by johlju** [comment]
@BernieWhite can you propose a schema.mof with what you are suggesting?
