### ISSUE TITLE
How do I go to "Suceess, Failure" from "No auditing" in Local security Policy (Win10 1803) using AuditPolicyDcs for "Audit object access" policy

### ISSUE THREAD

**Issue by LeonIHOP** [athaynes/xAuditPolicy#53]
How do I go to "Suceess, Failure" from "No auditing" in Local security Policy (Win10 1803) using AuditPolicyDcs for "Audit object access" policy

**Comment by athaynes** [comment]
[This](https://github.com/PowerShell/AuditPolicyDsc/blob/dev/Examples/Sample_AuditPolicySubcategory.ps1) example should get you there. Just set both Success and Failure flags to present.

**Comment by LeonIHOP** [comment]
Thanks Adam! 
Which of the following Object access subcategories would I need to use to control "Audit object access"

######Object Access                         = "6997984A-797A-11D9-BED3-505054503030";
    "File System"                            = "0CCE921D-69AE-11D9-BED3-505054503030";
    "Registry"                               = "0CCE921E-69AE-11D9-BED3-505054503030";
    "Kernel Object"                          = "0CCE921F-69AE-11D9-BED3-505054503030";
    "SAM"                                    = "0CCE9220-69AE-11D9-BED3-505054503030";
    "Certification Services"                 = "0CCE9221-69AE-11D9-BED3-505054503030";
    "Application Generated"                  = "0CCE9222-69AE-11D9-BED3-505054503030";
    "Handle Manipulation"                    = "0CCE9223-69AE-11D9-BED3-505054503030";
    "File Share"                             = "0CCE9224-69AE-11D9-BED3-505054503030";
    "Filtering Platform Packet Drop"         = "0CCE9225-69AE-11D9-BED3-505054503030";
    "Filtering Platform Connection"          = "0CCE9226-69AE-11D9-BED3-505054503030";
    "Other Object Access Events"             = "0CCE9227-69AE-11D9-BED3-505054503030";
    "Detailed File Share"                    = "0CCE9244-69AE-11D9-BED3-505054503030";
    "Removable Storage"                      = "0CCE9245-69AE-11D9-BED3-505054503030";
    "Central Policy Staging"                 = "0CCE9246-69AE-11D9-BED3-505054503030";

**Comment by gaelcolas** [comment]
Hi @lpolyak68, 

You probably want all of those sub category, right?
```cmd
PS C:\src> auditpol --% /list /subcategory:"Object Access"
Category/Subcategory
Object Access
  File System
  Registry
  Kernel Object
  SAM
  Certification Services
  Application Generated
  Handle Manipulation
  File Share
  Filtering Platform Packet Drop
  Filtering Platform Connection
  Other Object Access Events
  Detailed File Share
  Removable Storage
  Central Policy Staging
```
